
#' Bayesian Differential Expression Analysis for Proteomics
#' This is the primary function for performing Bayesian differential expression analysis
#' on proteomics datasets.
#'
#' @param values A numeric matrix or data.frame of log2 intensities. Rows correspond to proteins
#' (with protein IDs as rownames), and columns correspond to samples. Each row must
#' contain at least one non-NA value.
#'
#' @param groups A factor vector specifying the group assignment for each sample.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`,
#'   specifying which pairwise group comparisons to perform.
#' @param filter4NAs Logical. If `TRUE`, filters the dataset to retain only rows (proteins)
#'   that contain at least one missing value.
#' @param threshold Numeric. The missing proportion threshold that determines
#'   which missingness mechanism model to use. If the protein's missingness is < `threshold`,
#'   the logistic model is used; otherwise, the truncated normal model is used.
#' @param parallel Logical. If `TRUE`, the analysis for each protein is
#'   parallelized across multiple CPU cores.
#' @param ROPE A numeric vector of length 2 specifying the lower and upper bounds of the
#'   Region of Practical Equivalence (ROPE). Values within this interval are considered
#'   practically equivalent to the null value (e.g., `c(-0.1, 0.1)` for log fold change).
#' @param n.adapt Integer. Number of iterations for the adaptive phase.
#' @param burn.in An integer denoting number of burn-in steps.
#' @param n.iter Integer. Number of iterations after burn-in.
#' @param n.chains Integer. Number of MCMC chains to run.
#' @param mcmcDiag Logical. If `TRUE`, the output includes additional MCMC diagnostics.
#' @return A list of tables containing model results for each contrast specified in comparisons.
#'
#' @seealso \code{\link{plotPost}} for visualizing the posterior distribution of a single protein.
#'
#' @export
#'
#' @examples
#'
#' my_data <- matrix(rnorm(1200), nrow = 300, ncol = 4)
#' rownames(my_data) <- paste0("Protein_", 1:300)
#' colnames(my_data) <- paste0("Sample_", 1:4)
#' groups_factor <- factor(c("Control", "Control", "Treatment", "Treatment"))
#'
#'
#' # Create a contrast matrix
#' my_contrasts <- limma::makeContrasts(
#' Treatment_vs_Control = Treatment - Control,
#' levels = groups_factor
#' )
#'
#' # Run the analysis
#' output <- BayesMissingModel(
#' values = my_data,
#' groups = groups_factor,
#' comparisons = my_contrasts,
#' parallel = FALSE
#' )
#'
#'


BayesMissingModel <-  function(values, groups, comparisons, filter4NAs = FALSE, threshold = 0, parallel = TRUE, ROPE = c(-0.2,0.2),
                               n.adapt = 1000,burn.in = 500, n.iter = 10000, n.chains = 2, mcmcDiag = FALSE){

  zS <- zeroState(values)
  s1 <- sigma1(values)
  s2P <- sigma_p2params(values, groups)
  sjp2P <- sigma_jp2params(values, s2P$r)
  d <- default_val(values, sjp2P$group_vars_all)

  bayesResults <- list()
  for (contrast in colnames(comparisons)){
    cd <- setupContrasts(values,
                         comparisons,
                         contrast,
                         groups,
                         filter4NAs)

    bayesResults[[contrast]] <- runModel(cd, s2P, sjp2P, zS, s1, d, n.chains, burn.in, n.iter, n.adapt, parallel,
                                         mcmcDiag, threshold, ROPE)
  }

  return(bayesResults)
}

#' @export
setGeneric("BayesianMissingAggregate", function(obj,...) standardGeneric("BayesianMissingAggregate"))

#' @title BayesianMissingAggregate
#' @description QFeatures integration, runs model fitting for all specified comparisons and adds them to existing QFeatures object.
#'
#' @param obj A QFeatures instance.
#' @param i A string or integer specifying the element of 'obj' that contains the log abundance intensities that will be modeled.
#' @param fcol A string  that denotes feature variable of assay ‘i’ defining how to summarise the features.
#' @param gcol A string or integer specifying which column of colData(obj) denotes sample -> group assignments
#' @param contrastPrefix A string that prefixes model results names.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`,
#'   specifying which pairwise group comparisons to perform.
#' @param threshold Numeric. The missing proportion threshold that determines
#'   which missingness mechanism model to use. If the protein's missingness is < `threshold`,
#'   the logistic model is used; otherwise, the truncated normal model is used.
#' @param parallel Logical. If `TRUE`, the analysis for each protein is
#'   parallelized across multiple CPU cores.
#' @param ROPE A numeric vector of length 2 specifying the lower and upper bounds of the
#'   Region of Practical Equivalence (ROPE). Values within this interval are considered
#'   practically equivalent to the null value (e.g., `c(-0.1, 0.1)` for log fold change).
#' @param n.adapt Integer. Number of iterations for the adaptive phase.
#' @param burn.in An integer denoting number of burn-in steps.
#' @param n.iter Integer. Number of iterations after burn-in.
#' @param n.chains Integer. Number of MCMC chains to run.
#' @param mcmcDiag Logical. If `TRUE`, the output includes additional MCMC diagnostics.
#' @return Original QFeatures object 'obj' with model results attached.
#'
#' @seealso \code{\link{BayesMissingModel}}
#' @docType methods
#' @name BayesianMissingAggregate
#' @aliases BayesianMissingAggregate,QFeatures-method
#' @export
#' 
#' @examples
#'
#' library(QFeatures)
#' my_data <- matrix(rnorm(1200), nrow = 300, ncol = 4)
#' rownames(my_data) <- paste0("Protein_", 1:300)
#' colnames(my_data) <- paste0("Sample_", 1:4)
#' groups_factor <- factor(c("Control", "Control", "Treatment", "Treatment"))
#'
#'
#' # Create a contrast matrix
#' my_contrasts <- limma::makeContrasts(
#' Treatment_vs_Control = Treatment - Control,
#' levels = groups_factor
#' )
#'
#' # Run the analysis
#' 
#' qf <- readQFeatures(my_data, quantCols = colnames(my_data), name = 'Log2Values')
#' colData(qf)$condition <- groups_factor
#' rowData(qf[['Log2Values']])$Protein.Names <- rownames(my_data)
#' qf <- BayesianMissingAggregate(qf, i = 'Log2Values', 
#' fcol = 'Protein.Names',
#' comparisons = my_contrasts, 
#' gcol = 'condition', 
#' parallel = FALSE, n.chains = 4, mcmcDiag = TRUE)
#'
#'

setMethod(
  "BayesianMissingAggregate", "QFeatures",
  function(obj, i, fcol, comparisons, gcol, contrastPrefix = 'BayesMissingOutput - ', threshold = 0, parallel = TRUE, ROPE = c(-0.2,0.2),
           n.adapt = 1000,burn.in = 500, n.iter = 10000, n.chains = 2, mcmcDiag = FALSE){

    if (is.null(obj[[i]])) stop("QFeatures object does not contain assay ", i)

    if (!fcol %in% colnames(SummarizedExperiment::rowData(obj[[i]])))
      stop("The rowData does not contain variable '", fcol, "'.")

    if (!gcol %in% colnames(SummarizedExperiment::colData(obj)))
      stop("The colData does not contain variable '", gcol, "'.")

    log2all.df <- as.data.frame(SummarizedExperiment::assay(obj[[i]]))
    rownames(log2all.df) <- SummarizedExperiment::rowData(obj[[i]])[,fcol]
    
    groups <- as.factor(SummarizedExperiment::colData(obj)[,gcol])

    results <- BayesMissingModel(values = log2all.df,
                                 groups = groups,
                                 comparisons = comparisons,
                                 filter4NAs = FALSE, #Filter4NAs must be false so that results align with rowData.
                                 threshold = threshold,
                                 parallel = parallel,
                                 ROPE = ROPE,
                                 n.adapt = n.adapt,
                                 burn.in = burn.in,
                                 n.iter = n.iter,
                                 n.chains = n.chains,
                                 mcmcDiag = mcmcDiag)

    for (contrast in colnames(comparisons)){
      SummarizedExperiment::rowData(obj[[i]])[[paste0(contrastPrefix, contrast)]] <- results[[contrast]]
    }

    return(obj)
  }
)

#' @title BayesianMissingAggregate
#' @description SingleCellExperiment integration, runs model fitting for all specified comparisons and adds them to existing SingleCellExperiment object.
#'
#' @param obj A SingleCellExperiment instance.
#' @param fcol A string  that denotes feature variable of rowData(obj) defining how to summarise the features.
#' @param gcol A string or integer specifying which column of colData(obj) denotes sample -> group assignments
#' @param contrastPrefix A string that prefixes model results names.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`,
#'   specifying which pairwise group comparisons to perform.
#' @param threshold Numeric. The missing proportion threshold that determines
#'   which missingness mechanism model to use. If the protein's missingness is < `threshold`,
#'   the logistic model is used; otherwise, the truncated normal model is used.
#' @param parallel Logical. If `TRUE`, the analysis for each protein is
#'   parallelized across multiple CPU cores.
#' @param ROPE A numeric vector of length 2 specifying the lower and upper bounds of the
#'   Region of Practical Equivalence (ROPE). Values within this interval are considered
#'   practically equivalent to the null value (e.g., `c(-0.1, 0.1)` for log fold change).
#' @param n.adapt Integer. Number of iterations for the adaptive phase.
#' @param burn.in An integer denoting number of burn-in steps.
#' @param n.iter Integer. Number of iterations after burn-in.
#' @param n.chains Integer. Number of MCMC chains to run.
#' @param mcmcDiag Logical. If `TRUE`, the output includes additional MCMC diagnostics.
#' @return Original SingleCellExperiment object 'obj' with model results attached.
#'
#' @seealso \code{\link{BayesMissingModel}}
#' @docType methods
#' @name BayesianMissingAggregate
#' @aliases BayesianMissingAggregate,SingleCellExperiment-method
#' @export
#' 
#' @examples
#' leduc2022 <- scpdata::leduc2022_pSCoPE()
#' leduc2022.proc <- MultiAssayExperiment::getWithColData(leduc2022, 'proteins_norm2')
#' L <- limma::makeContrasts(contrasts = "Monocyte - Melanoma", levels = c("Monocyte", "Melanoma"))
#' leduc2022.proc <- BayesianMissingAggregate(leduc2022.proc,
#' fcol = 'Leading.razor.protein.symbol',
#' comparisons = L,
#' gcol = 'SampleType',
#' parallel = FALSE, n.chains = 4, mcmcDiag = TRUE)
#' 

setMethod(
  "BayesianMissingAggregate", "SingleCellExperiment",
  function(obj, fcol, comparisons, gcol, contrastPrefix = 'BayesMissingOutput: ', threshold = 0, parallel = TRUE, ROPE = c(-0.2,0.2), 
           n.adapt = 500, burn.in = 500, n.iter = 10000, n.chains = 2, mcmcDiag = FALSE){
    
    if (!fcol %in% colnames(SummarizedExperiment::rowData(obj)))
      stop("The rowData does not contain variable '", fcol, "'.")
    
    if (!gcol %in% colnames(SummarizedExperiment::colData(obj)))
      stop("The colData does not contain variable '", gcol, "'.")
    
    log2all.df <- as.data.frame(SummarizedExperiment::assay(obj))
    rownames(log2all.df) <- SummarizedExperiment::rowData(obj)[,fcol]
    
    groups <- as.factor(SummarizedExperiment::colData(obj)[,gcol])
    
    results <- BayesMissingModel(values = log2all.df, 
                                 groups = groups, 
                                 comparisons = comparisons, 
                                 filter4NAs = FALSE, #Filter4NAs must be false so that results align with rowData.
                                 threshold = threshold,
                                 parallel = parallel, 
                                 ROPE = ROPE,
                                 n.adapt = n.adapt, 
                                 burn.in = burn.in, 
                                 n.iter = n.iter, 
                                 n.chains = n.chains,
                                 mcmcDiag = mcmcDiag)
    
    for (contrast in colnames(comparisons)){
      SummarizedExperiment::rowData(obj)[[paste0(contrastPrefix, contrast)]] <- results[[contrast]]
    }
    
    return(obj)
  }
)

