
#' Validate the sample-to-group mapping and contrast matrix
#'
#' Checks the inputs that the model silently depended on before: that `groups`
#' labels every column of `values`, that at least two groups are actually
#' populated, and that every group named by a contrast exists in `groups`.
#'
#' @param values A numeric matrix or data.frame of log2 intensities, samples in columns.
#' @param groups A factor vector specifying the group assignment for each sample.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`.
#'   `NULL` for callers such as `plotPost()` that name a single contrast
#'   directly, in which case only `values` and `groups` are checked.
#' @return `groups`, coerced to a factor.
#' @keywords internal


validateGroups <- function(values, groups, comparisons = NULL){

  if (is.null(dim(values)) || length(dim(values)) != 2L)
    stop("'values' must be a matrix or data.frame with samples in columns.")

  if (!is.factor(groups)) groups <- factor(groups)

  if (ncol(values) != length(groups))
    stop("'groups' must have one entry per column of 'values': ",
         "'values' has ", ncol(values), " columns but 'groups' has length ",
         length(groups), ".")

  if (anyNA(groups))
    stop("'groups' must not contain NA; every column of 'values' must be ",
         "assigned to a group.")

  group_sizes <- table(groups)
  populated <- names(group_sizes)[group_sizes > 0]
  if (length(populated) < 2L)
    stop("'groups' must contain at least two non-empty groups; found ",
         length(populated),
         if (length(populated) > 0) paste0(" ('", paste(populated, collapse = "', '"), "')") else "",
         ".")

  if (is.null(comparisons)) return(groups)

  if (is.null(dim(comparisons)) || is.null(colnames(comparisons)))
    stop("'comparisons' must be a contrast matrix with named columns, ",
         "as returned by limma::makeContrasts().")

  # Groups a contrast actually weights; a zero row is simply not compared.
  contrasted <- rownames(comparisons)[rowSums(comparisons != 0, na.rm = TRUE) > 0]
  missing_groups <- setdiff(contrasted, populated)
  if (length(missing_groups) > 0)
    stop("group(s) named in 'comparisons' are absent from 'groups': '",
         paste(missing_groups, collapse = "', '"), "'.")

  # Each contrast is resolved to a single pair of groups, so a column that
  # weights anything else - an average such as (A + B) / 2 - C, or two groups
  # at +1 - has no meaning here and would otherwise fail obscurely inside
  # setupContrasts().
  for (nm in colnames(comparisons)) {
    w <- comparisons[, nm]
    if (!all(w %in% c(0, 1, -1)) ||
        sum(w == 1, na.rm = TRUE) != 1L || sum(w == -1, na.rm = TRUE) != 1L)
      stop("contrast '", nm, "' is not a pairwise comparison: every column of ",
           "'comparisons' must weight exactly one group +1 and one group -1, ",
           "as in limma::makeContrasts(\"B - A\", levels = levels(groups)).")
  }

  groups
}


#' Bayesian Differential Expression Analysis for Proteomics
#' This is the primary function for performing Bayesian differential expression analysis
#' on proteomics datasets.
#'
#' @param values A numeric matrix or data.frame of log2 intensities. Rows correspond to proteins
#' (with protein IDs as rownames), and columns correspond to samples. Each row must
#' contain at least one non-NA value. Columns must be in the same order as `groups`,
#' but need not be grouped together: samples of a group may be interleaved.
#'
#' @param groups A factor vector specifying the group assignment for each sample,
#'   one entry per column of `values`. Groups may contain unequal numbers of
#'   samples; unbalanced designs are fully supported.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`,
#'   specifying which pairwise group comparisons to perform.
#' @param filter4NAs Logical. If `TRUE`, filters the dataset to retain only rows (proteins)
#'   that contain at least one missing value.
#' @param threshold Numeric. The parameter that determines
#'   which missingness mechanism model to use. If `threshold = 1`,
#'   the logistic model is used; If `threshold = 0`, the truncated normal model is used.
#' @param parallel Logical. If `TRUE`, the analysis for each protein is
#'   parallelized across multiple CPU cores.
#' @param ROPE A numeric vector of length 2 specifying the lower and upper bounds of the
#'   Region of Practical Equivalence (ROPE). Values within this interval are considered
#'   practically equivalent to the null value (e.g., `c(-0.1, 0.1)` for log fold change).
#' @param n.adapt Integer. Number of iterations for the adaptive phase.
#' @param burn.in An integer denoting number of burn-in steps.
#' @param n.iter Integer. Number of iterations after burn-in.
#' @param n.chains Integer. Number of MCMC chains to run.
#' @param mcmcDiag Logical. If `TRUE`, the output includes additional MCMC diagnostics.
#' @return A list of tables containing model results for each contrast specified in comparisons.
#'
#' @seealso \code{\link{plotPost}} for visualizing the posterior distribution of a single protein.
#'
#' @export
#'
#' @examples
#'
#' my_data <- matrix(rnorm(1200), nrow = 300, ncol = 4)
#' rownames(my_data) <- paste0("Protein_", 1:300)
#' colnames(my_data) <- paste0("Sample_", 1:4)
#' groups_factor <- factor(c("Control", "Control", "Treatment", "Treatment"))
#'
#'
#' # Create a contrast matrix
#' my_contrasts <- limma::makeContrasts(
#' Treatment_vs_Control = Treatment - Control,
#' levels = groups_factor
#' )
#'
#' # Run the analysis
#' output <- BayesMissingModel(
#' values = my_data,
#' groups = groups_factor,
#' comparisons = my_contrasts,
#' parallel = FALSE
#' )
#'
#'


BayesMissingModel <-  function(values, groups, comparisons, filter4NAs = FALSE, threshold = 0, parallel = TRUE, ROPE = c(-0.2,0.2),
                               n.adapt = 1000,burn.in = 500, n.iter = 10000, n.chains = 2, mcmcDiag = FALSE){

  groups <- validateGroups(values, groups, comparisons)

  zS <- zeroState(values)
  s1 <- sigma1(values)
  s2P <- sigma_p2params(values, groups)
  sjp2P <- sigma_jp2params(values, groups)
  d <- default_val(values, sjp2P$group_vars_all)

  bayesResults <- list()
  for (contrast in colnames(comparisons)){
    cd <- setupContrasts(values,
                         comparisons,
                         contrast,
                         groups,
                         filter4NAs)

    bayesResults[[contrast]] <- runModel(cd, s2P, sjp2P, zS, s1, d, n.chains, burn.in, n.iter, n.adapt, parallel,
                                         mcmcDiag, threshold, ROPE)
  }

  return(bayesResults)
}


#' @title BayesianMissingAggregate
#' @description QFeatures integration, runs model fitting for all specified comparisons and adds them to existing QFeatures object.
#'
#' @param obj A QFeatures instance.
#' @param ... Additional arguments passed to control MCMC settings.
#' @param i A string or integer specifying the element of 'obj' that contains the log abundance intensities that will be modeled.
#' @param fcol A string  that denotes feature variable of assay ‘i’ defining how to summarise the features.
#' @param gcol A string or integer specifying which column of colData(obj) denotes sample -> group assignments
#' @param contrastPrefix A string that prefixes model results names.
#' @param comparisons A contrast matrix, generated by `limma::makeContrasts`,
#'   specifying which pairwise group comparisons to perform.
#' @param threshold Numeric. The parameter that determines
#'   which missingness mechanism model to use. If `threshold = 1`,
#'   the logistic model is used; If `threshold = 0`, the truncated normal model is used.
#' @param parallel Logical. If `TRUE`, the analysis for each protein is
#'   parallelized across multiple CPU cores.
#' @param ROPE A numeric vector of length 2 specifying the lower and upper bounds of the
#'   Region of Practical Equivalence (ROPE). Values within this interval are considered
#'   practically equivalent to the null value (e.g., `c(-0.1, 0.1)` for log fold change).
#' @param n.adapt Integer. Number of iterations for the adaptive phase.
#' @param burn.in An integer denoting number of burn-in steps.
#' @param n.iter Integer. Number of iterations after burn-in.
#' @param n.chains Integer. Number of MCMC chains to run.
#' @param mcmcDiag Logical. If `TRUE`, the output includes additional MCMC diagnostics.
#' @return Original QFeatures object 'obj' with model results attached.
#'
#' @seealso \code{\link{BayesMissingModel}}
#' @docType methods
#' @name BayesianMissingAggregate
#' @aliases BayesianMissingAggregate
#' @export


setGeneric("BayesianMissingAggregate", function(obj,...) standardGeneric("BayesianMissingAggregate"))

setMethod(
  "BayesianMissingAggregate", "QFeatures",
  function(obj, i, fcol, comparisons, gcol, contrastPrefix = 'BayesMissingOutput - ', threshold = 0, parallel = TRUE, ROPE = c(-0.2,0.2),
           n.adapt = 1000,burn.in = 500, n.iter = 10000, n.chains = 2, mcmcDiag = FALSE){

    if (is.null(obj[[i]])) stop("QFeatures object does not contain assay ", i)

    if (!fcol %in% colnames(QFeatures::rowData(obj[[i]])))
      stop("The rowData does not contain variable '", fcol, "'.")

    if (!gcol %in% colnames(QFeatures::colData(obj)))
      stop("The colData does not contain variable '", gcol, "'.")

    log2all.df <- as.data.frame(QFeatures::assay(obj[[i]]))
    rownames(log2all.df) <- QFeatures::rowData(obj[[i]])[,fcol]

    results <- BayesMissingModel(values = log2all.df,
                                 groups = QFeatures::colData(obj)[,gcol],
                                 comparisons = comparisons,
                                 filter4NAs = FALSE, #Filter4NAs must be false so that results align with rowData.
                                 threshold = threshold,
                                 parallel = parallel,
                                 ROPE = ROPE,
                                 n.adapt = n.adapt,
                                 burn.in = burn.in,
                                 n.iter = n.iter,
                                 n.chains = n.chains,
                                 mcmcDiag = mcmcDiag)

    for (contrast in colnames(comparisons)){
      QFeatures::rowData(obj[[i]])[[paste0(contrastPrefix, contrast)]] <- results[[contrast]]
    }

    return(obj)
  }
)
